app = "dell-lingering-brook-354"
primary_region = "sjc"
swap_size_mb = 512
kill_signal = "SIGINT"
kill_timeout = 5
processes = []
[mounts]
  source = "myapp_data"
  destination = "/data"
[build]
  dockerfile = './Dockerfile'

[build.args]
  BP_CPYTHON_VERSION = "3.8.17"
[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
